import type { Book } from './types';

export const mockBooks: Book[] = [
  {
    id: '1',
    title: 'The Great Gatsby',
    author: 'F. Scott Fitzgerald',
    coverImage: 'https://placehold.co/300x400',
    fileType: 'EPUB',
    content: "In my younger and more vulnerable years my father gave me some advice that I've been turning over in my mind ever since. 'Whenever you feel like criticizing any one,' he told me, 'just remember that all the people in this world haven't had the advantages that you've had.'",
  },
  {
    id: '2',
    title: 'To Kill a Mockingbird',
    author: 'Harper Lee',
    coverImage: 'https://placehold.co/300x400',
    fileType: 'PDF',
    content: "When he was nearly thirteen, my brother Jem got his arm badly broken at the elbow. When it healed, and Jem's fears of never being able to play football were assuaged, he was seldom self-conscious about his injury.",
  },
  {
    id: '3',
    title: '1984',
    author: 'George Orwell',
    coverImage: 'https://placehold.co/300x400',
    fileType: 'MOBI',
    content: "It was a bright cold day in April, and the clocks were striking thirteen. Winston Smith, his chin nuzzled into his breast in an effort to escape the vile wind, slipped quickly through the glass doors of Victory Mansions, though not quickly enough to prevent a swirl of gritty dust from entering along with him.",
  },
  {
    id: '4',
    title: 'Pride and Prejudice',
    author: 'Jane Austen',
    coverImage: 'https://placehold.co/300x400',
    fileType: 'DOCX',
    content: "It is a truth universally acknowledged, that a single man in possession of a good fortune, must be in want of a wife. However little known the feelings or views of such a man may be on his first entering a neighbourhood, this truth is so well fixed in the minds of the surrounding families, that he is considered the rightful property of some one or other of their daughters.",
  },
    {
    id: '5',
    title: 'The Hobbit',
    author: 'J.R.R. Tolkien',
    coverImage: 'https://placehold.co/300x400',
    fileType: 'EPUB',
    content: "In a hole in the ground there lived a hobbit. Not a nasty, dirty, wet hole, filled with the ends of worms and an oozy smell, nor yet a dry, bare, sandy hole with nothing in it to sit down on or to eat: it was a hobbit-hole, and that means comfort.",
  },
  {
    id: '6',
    title: 'A Tale of Two Cities',
    author: 'Charles Dickens',
    coverImage: 'https://placehold.co/300x400',
    fileType: 'TXT',
    content: "It was the best of times, it was the worst of times, it was the age of wisdom, it was the age of foolishness, it was the epoch of belief, it was the epoch of incredulity, it was the season of Light, it was the season of Darkness, it was the spring of hope, it was the winter of despair.",
  },
  {
    id: '7',
    title: 'האריה והעכבר',
    author: 'איזופוס',
    coverImage: 'https://placehold.co/300x400',
    fileType: 'TXT',
    content: "אריה ישן ביער. עכבר קטן התרוצץ לידו והעיר אותו. האריה הכועס תפס את העכבר ורצה לאכול אותו. 'בבקשה, שחרר אותי,' צייץ העכבר. 'אולי יום אחד אוכל לעזור לך.' האריה צחק ושיחרר אותו. כמה ימים לאחר מכן, ציידים לכדו את האריה ברשת. העכבר שמע את שאגותיו, רץ אל הרשת, וכרסם את החבלים עד שהאריה היה חופשי. 'אתה רואה,' אמר העכבר, 'גם עכבר קטן יכול לעזור לאריה גדול.'",
  },
];
