// This is a custom service worker file that uses Workbox
// to enable offline functionality for the PWA.

import { precacheAndRoute } from 'workbox-precaching';
import { registerRoute } from 'workbox-routing';
import { StaleWhileRevalidate, CacheFirst } from 'workbox-strategies';
import { ExpirationPlugin } from 'workbox-expiration';

declare const self: ServiceWorkerGlobalScope;

// Precache all the assets generated by the build process.
// Their URLs are injected into the manifest file during the build.
precacheAndRoute(self.__WB_MANIFEST);

// Runtime caching for Google Fonts
registerRoute(
  /^https://fonts\.googleapis\.com\/.*/i,
  new StaleWhileRevalidate({
    cacheName: 'google-fonts-stylesheets',
  })
);

registerRoute(
  /^https:\/\/fonts\.gstatic\.com\/.*/i,
  new StaleWhileRevalidate({
    cacheName: 'google-fonts-webfonts',
    plugins: [
      // Cache fonts for one year
      new ExpirationPlugin({
        maxEntries: 30,
        maxAgeSeconds: 60 * 60 * 24 * 365,
      }),
    ],
  })
);

// Cache images with a CacheFirst strategy
registerRoute(
  /\.(?:png|gif|jpg|jpeg|svg|ico)$/,
  new CacheFirst({
    cacheName: 'images',
    plugins: [
      new ExpirationPlugin({
        maxEntries: 60,
        maxAgeSeconds: 30 * 24 * 60 * 60, // 30 Days
      }),
    ],
  })
);

// Cache pages with a StaleWhileRevalidate strategy
// This will serve pages from the cache first for speed,
// and update them in the background.
registerRoute(
  ({ request }) => request.mode === 'navigate',
  new StaleWhileRevalidate({
    cacheName: 'pages',
    plugins: [
      new ExpirationPlugin({
        maxEntries: 50,
      }),
    ],
  })
);
